# Generated by Django 3.1 on 2020-11-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
